//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingVSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportOrder
    {
        public int ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string CntrSize { get; set; }
        public string CntrNo { get; set; }
        public Nullable<int> TripID { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string staff_cd { get; set; }
        public string Status { get; set; }
        public string SendSMS { get; set; }
    }
}
