//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingVSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int ID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string FeeName { get; set; }
        public Nullable<int> FeeAmount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CntrSize { get; set; }
        public Nullable<int> Total { get; set; }
        public string staff_cd { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string Status { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
