//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingVSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string Note { get; set; }
        public string Bill { get; set; }
        public string Booking { get; set; }
        public string Type { get; set; }
        public string staff_cd { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string Status { get; set; }
        public string Shipping { get; set; }
        public string ChangePlan { get; set; }
        public Nullable<System.DateTime> TransportDate { get; set; }
        public string PickupYard { get; set; }
        public string StuffingWarehouse { get; set; }
        public string StuffDate { get; set; }
        public string Commodity { get; set; }
        public string Inquiry { get; set; }
        public string Payer { get; set; }
        public string Weight { get; set; }
        public string Caller { get; set; }
    
        public virtual Consignee Consignee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
