//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingVSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckInfo
    {
        public int ID { get; set; }
        public string XeTot { get; set; }
        public string XeCoKeHoach { get; set; }
        public string XeSuaChua { get; set; }
        public string XeChuaCoTai { get; set; }
        public string XeLuuChuHang { get; set; }
        public string XeThueNgoaiHue { get; set; }
        public string XeThueNgoaiQN { get; set; }
        public string XeThueNgoaiDN { get; set; }
        public string ThieuXeHue { get; set; }
        public string ThieuXeQN { get; set; }
        public string ThieuXeDN { get; set; }
        public System.DateTime Ngay { get; set; }
        public string staff_cd { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
