//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingVSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string License { get; set; }
        public string staff_cd { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string LicenseExpire { get; set; }
        public string CMND { get; set; }
        public string Address { get; set; }
        public string LicenseDate { get; set; }
        public string Birthday { get; set; }
        public string ZaloId { get; set; }
    }
}
