//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingVSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trailer
    {
        public int ID { get; set; }
        public string TrailerNo { get; set; }
        public string ExpireDate { get; set; }
        public string staff_cd { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string Weight { get; set; }
    }
}
