//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingVSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        public int ID { get; set; }
        public string TruckNo { get; set; }
        public string Status { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> TrailerID { get; set; }
        public string Expire { get; set; }
        public string staff_cd { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string Transit { get; set; }
        public Nullable<bool> OwnRent { get; set; }
    }
}
