//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingVSM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TruckingVSMEntities : DbContext
    {
        public TruckingVSMEntities()
            : base("name=TruckingVSMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Consignee> Consignees { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<FeeByConsignee> FeeByConsignees { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ShippingLine> ShippingLines { get; set; }
        public virtual DbSet<Trailer> Trailers { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionDetail> TransactionDetails { get; set; }
        public virtual DbSet<TransportOrder> TransportOrders { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<TruckInfo> TruckInfoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<StandardFee> StandardFees { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    
        public virtual int VT_AddDetailFast(Nullable<int> transactionID, Nullable<int> consigneeID, Nullable<int> locationID, Nullable<int> quantity, string cntrSize, string staffcd, Nullable<System.DateTime> updatetime)
        {
            var transactionIDParameter = transactionID.HasValue ?
                new ObjectParameter("TransactionID", transactionID) :
                new ObjectParameter("TransactionID", typeof(int));
    
            var consigneeIDParameter = consigneeID.HasValue ?
                new ObjectParameter("ConsigneeID", consigneeID) :
                new ObjectParameter("ConsigneeID", typeof(int));
    
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            var cntrSizeParameter = cntrSize != null ?
                new ObjectParameter("CntrSize", cntrSize) :
                new ObjectParameter("CntrSize", typeof(string));
    
            var staffcdParameter = staffcd != null ?
                new ObjectParameter("staffcd", staffcd) :
                new ObjectParameter("staffcd", typeof(string));
    
            var updatetimeParameter = updatetime.HasValue ?
                new ObjectParameter("updatetime", updatetime) :
                new ObjectParameter("updatetime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VT_AddDetailFast", transactionIDParameter, consigneeIDParameter, locationIDParameter, quantityParameter, cntrSizeParameter, staffcdParameter, updatetimeParameter);
        }
    
        public virtual int VT_AddNewTrip(Nullable<int> truckId, Nullable<int> driverId, string cntr1, string cntr2, Nullable<int> orderId1, Nullable<int> orderId2, Nullable<System.DateTime> createDate, string staff_cd, string status, string note)
        {
            var truckIdParameter = truckId.HasValue ?
                new ObjectParameter("TruckId", truckId) :
                new ObjectParameter("TruckId", typeof(int));
    
            var driverIdParameter = driverId.HasValue ?
                new ObjectParameter("DriverId", driverId) :
                new ObjectParameter("DriverId", typeof(int));
    
            var cntr1Parameter = cntr1 != null ?
                new ObjectParameter("Cntr1", cntr1) :
                new ObjectParameter("Cntr1", typeof(string));
    
            var cntr2Parameter = cntr2 != null ?
                new ObjectParameter("Cntr2", cntr2) :
                new ObjectParameter("Cntr2", typeof(string));
    
            var orderId1Parameter = orderId1.HasValue ?
                new ObjectParameter("OrderId1", orderId1) :
                new ObjectParameter("OrderId1", typeof(int));
    
            var orderId2Parameter = orderId2.HasValue ?
                new ObjectParameter("OrderId2", orderId2) :
                new ObjectParameter("OrderId2", typeof(int));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var staff_cdParameter = staff_cd != null ?
                new ObjectParameter("staff_cd", staff_cd) :
                new ObjectParameter("staff_cd", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VT_AddNewTrip", truckIdParameter, driverIdParameter, cntr1Parameter, cntr2Parameter, orderId1Parameter, orderId2Parameter, createDateParameter, staff_cdParameter, statusParameter, noteParameter);
        }
    
        public virtual ObjectResult<VT_AuthenticateUser_Result> VT_AuthenticateUser(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_AuthenticateUser_Result>("VT_AuthenticateUser", userParameter, passParameter);
        }
    
        public virtual ObjectResult<VT_CheckBookExist_Result> VT_CheckBookExist(string book, string bill)
        {
            var bookParameter = book != null ?
                new ObjectParameter("book", book) :
                new ObjectParameter("book", typeof(string));
    
            var billParameter = bill != null ?
                new ObjectParameter("bill", bill) :
                new ObjectParameter("bill", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_CheckBookExist_Result>("VT_CheckBookExist", bookParameter, billParameter);
        }
    
        public virtual int VT_CompleteTrip(string cntrno, Nullable<int> id, string truckno, Nullable<System.DateTime> ctime, string status, string note, Nullable<decimal> weight)
        {
            var cntrnoParameter = cntrno != null ?
                new ObjectParameter("cntrno", cntrno) :
                new ObjectParameter("cntrno", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var trucknoParameter = truckno != null ?
                new ObjectParameter("truckno", truckno) :
                new ObjectParameter("truckno", typeof(string));
    
            var ctimeParameter = ctime.HasValue ?
                new ObjectParameter("ctime", ctime) :
                new ObjectParameter("ctime", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var weightParameter = weight.HasValue ?
                new ObjectParameter("Weight", weight) :
                new ObjectParameter("Weight", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VT_CompleteTrip", cntrnoParameter, idParameter, trucknoParameter, ctimeParameter, statusParameter, noteParameter, weightParameter);
        }
    
        public virtual int VT_DeleteDetailById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VT_DeleteDetailById", idParameter);
        }
    
        public virtual int VT_DeleteTransactionById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VT_DeleteTransactionById", idParameter);
        }
    
        public virtual int VT_DeleteTripByOrder(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VT_DeleteTripByOrder", idParameter);
        }
    
        public virtual int VT_ExtraDetail(Nullable<int> id, string feename, Nullable<int> quantity, Nullable<int> feeamount, Nullable<System.DateTime> updatetime, string cntrsize)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var feenameParameter = feename != null ?
                new ObjectParameter("feename", feename) :
                new ObjectParameter("feename", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var feeamountParameter = feeamount.HasValue ?
                new ObjectParameter("feeamount", feeamount) :
                new ObjectParameter("feeamount", typeof(int));
    
            var updatetimeParameter = updatetime.HasValue ?
                new ObjectParameter("updatetime", updatetime) :
                new ObjectParameter("updatetime", typeof(System.DateTime));
    
            var cntrsizeParameter = cntrsize != null ?
                new ObjectParameter("cntrsize", cntrsize) :
                new ObjectParameter("cntrsize", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VT_ExtraDetail", idParameter, feenameParameter, quantityParameter, feeamountParameter, updatetimeParameter, cntrsizeParameter);
        }
    
        public virtual ObjectResult<VT_GetAllConsigneeWithArea_Result> VT_GetAllConsigneeWithArea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetAllConsigneeWithArea_Result>("VT_GetAllConsigneeWithArea");
        }
    
        public virtual ObjectResult<VT_GetAllFeeByConsignee_Result> VT_GetAllFeeByConsignee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetAllFeeByConsignee_Result>("VT_GetAllFeeByConsignee");
        }
    
        public virtual ObjectResult<Nullable<int>> VT_GetCntr20(Nullable<System.DateTime> start, Nullable<System.DateTime> end, Nullable<int> id)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VT_GetCntr20", startParameter, endParameter, idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> VT_GetCntr40(Nullable<System.DateTime> start, Nullable<System.DateTime> end, Nullable<int> id)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VT_GetCntr40", startParameter, endParameter, idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> VT_GetCntr45(Nullable<System.DateTime> start, Nullable<System.DateTime> end, Nullable<int> id)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VT_GetCntr45", startParameter, endParameter, idParameter);
        }
    
        public virtual ObjectResult<VT_GetCompleteTrip_Result> VT_GetCompleteTrip()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetCompleteTrip_Result>("VT_GetCompleteTrip");
        }
    
        public virtual ObjectResult<VT_GetConsigneeWithArea_Result> VT_GetConsigneeWithArea(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetConsigneeWithArea_Result>("VT_GetConsigneeWithArea", idParameter);
        }
    
        public virtual ObjectResult<VT_GetCustomerWithTransaction_Result> VT_GetCustomerWithTransaction(Nullable<System.DateTime> start, Nullable<System.DateTime> end, Nullable<int> area)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetCustomerWithTransaction_Result>("VT_GetCustomerWithTransaction", startParameter, endParameter, areaParameter);
        }
    
        public virtual ObjectResult<VT_GetDetailById_Result> VT_GetDetailById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetDetailById_Result>("VT_GetDetailById", idParameter);
        }
    
        public virtual ObjectResult<VT_GetFeeByConsignee_Result> VT_GetFeeByConsignee(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetFeeByConsignee_Result>("VT_GetFeeByConsignee", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> VT_GetLiftingFee(Nullable<int> id, string cntrSize)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cntrSizeParameter = cntrSize != null ?
                new ObjectParameter("CntrSize", cntrSize) :
                new ObjectParameter("CntrSize", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VT_GetLiftingFee", idParameter, cntrSizeParameter);
        }
    
        public virtual ObjectResult<string> VT_GetNoteByName(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VT_GetNoteByName", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> VT_GetRevenueByCustomer(Nullable<System.DateTime> start, Nullable<System.DateTime> end, Nullable<int> id)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VT_GetRevenueByCustomer", startParameter, endParameter, idParameter);
        }
    
        public virtual ObjectResult<VT_GetSMSInfo_Result> VT_GetSMSInfo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetSMSInfo_Result>("VT_GetSMSInfo", idParameter);
        }
    
        public virtual ObjectResult<VT_GetTransacstionById_Result> VT_GetTransacstionById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTransacstionById_Result>("VT_GetTransacstionById", idParameter);
        }
    
        public virtual ObjectResult<VT_GetTransaction_Result> VT_GetTransaction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTransaction_Result>("VT_GetTransaction");
        }
    
        public virtual ObjectResult<VT_GetTransactionByDate_Result> VT_GetTransactionByDate(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTransactionByDate_Result>("VT_GetTransactionByDate", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetTransactionDetailById_Result> VT_GetTransactionDetailById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTransactionDetailById_Result>("VT_GetTransactionDetailById", idParameter);
        }
    
        public virtual ObjectResult<string> VT_GetTransportOrder(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VT_GetTransportOrder", typeParameter);
        }
    
        public virtual ObjectResult<VT_GetTripByDate_Result> VT_GetTripByDate(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTripByDate_Result>("VT_GetTripByDate", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetTripOrder_Result> VT_GetTripOrder(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTripOrder_Result>("VT_GetTripOrder", idParameter);
        }
    
        public virtual ObjectResult<VT_GetTruck_Result> VT_GetTruck()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTruck_Result>("VT_GetTruck");
        }
    
        public virtual ObjectResult<Nullable<int>> VT_RemainOrder(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VT_RemainOrder", typeParameter);
        }
    
        public virtual int VT_RemoveDetail(Nullable<int> id, string feename, Nullable<int> quantity, Nullable<int> feeamount, Nullable<System.DateTime> updatetime)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var feenameParameter = feename != null ?
                new ObjectParameter("feename", feename) :
                new ObjectParameter("feename", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var feeamountParameter = feeamount.HasValue ?
                new ObjectParameter("feeamount", feeamount) :
                new ObjectParameter("feeamount", typeof(int));
    
            var updatetimeParameter = updatetime.HasValue ?
                new ObjectParameter("updatetime", updatetime) :
                new ObjectParameter("updatetime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VT_RemoveDetail", idParameter, feenameParameter, quantityParameter, feeamountParameter, updatetimeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> VT_ReportAllRevenue(Nullable<System.DateTime> start, Nullable<System.DateTime> end, Nullable<int> id, string cntrsize)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cntrsizeParameter = cntrsize != null ?
                new ObjectParameter("cntrsize", cntrsize) :
                new ObjectParameter("cntrsize", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VT_ReportAllRevenue", startParameter, endParameter, idParameter, cntrsizeParameter);
        }
    
        public virtual int VT_ResetTotalPrice(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VT_ResetTotalPrice", idParameter);
        }
    
        public virtual ObjectResult<VT_RevenueByCustomer_Result> VT_RevenueByCustomer(Nullable<int> id, Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_RevenueByCustomer_Result>("VT_RevenueByCustomer", idParameter, startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_RevenueByMonth_Result> VT_RevenueByMonth(Nullable<System.DateTime> start, Nullable<System.DateTime> end, Nullable<int> id)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_RevenueByMonth_Result>("VT_RevenueByMonth", startParameter, endParameter, idParameter);
        }
    
        public virtual ObjectResult<string> VT_TransportOrderN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VT_TransportOrderN");
        }
    
        public virtual ObjectResult<string> VT_TransportOrderNN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VT_TransportOrderNN");
        }
    
        public virtual ObjectResult<string> VT_TransportOrderNX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VT_TransportOrderNX");
        }
    
        public virtual ObjectResult<string> VT_TransportOrderX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VT_TransportOrderX");
        }
    
        public virtual ObjectResult<VT_TripByDriver_Result> VT_TripByDriver(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_TripByDriver_Result>("VT_TripByDriver", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetTransacstionById_Result> VT_GetTransacstionById1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTransacstionById_Result>("VT_GetTransacstionById1", idParameter);
        }
    
        public virtual ObjectResult<VT_DailyPlan_Result> VT_DailyPlan(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_DailyPlan_Result>("VT_DailyPlan", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_DailyPlan_Result> VT_DailyPlan1(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_DailyPlan_Result>("VT_DailyPlan1", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetTripByDate_Result> VT_GetTripByDate1(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTripByDate_Result>("VT_GetTripByDate1", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetTransacstionById_Result> VT_GetTransacstionById2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTransacstionById_Result>("VT_GetTransacstionById2", idParameter);
        }
    
        public virtual ObjectResult<VT_GetTransactionByDate_Result> VT_GetTransactionByDate1(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTransactionByDate_Result>("VT_GetTransactionByDate1", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetTransacstionById_Result> VT_GetTransacstionById3(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTransacstionById_Result>("VT_GetTransacstionById3", idParameter);
        }
    
        public virtual ObjectResult<VT_GetTripByDate_Result> VT_GetTripByDate2(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTripByDate_Result>("VT_GetTripByDate2", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetTripByDate_Result> VT_GetTripByDate3(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTripByDate_Result>("VT_GetTripByDate3", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetSMSInfo_Result> VT_GetSMSInfo1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetSMSInfo_Result>("VT_GetSMSInfo1", idParameter);
        }
    
        public virtual ObjectResult<VT_GetSMSInfo_Result> VT_GetSMSInfo2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetSMSInfo_Result>("VT_GetSMSInfo2", idParameter);
        }
    
        public virtual ObjectResult<VT_GetFeeByConsignee_Result> VT_GetFeeByConsignee1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetFeeByConsignee_Result>("VT_GetFeeByConsignee1", idParameter);
        }
    
        public virtual ObjectResult<VT_DailyPlan_Result> VT_DailyPlan2(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_DailyPlan_Result>("VT_DailyPlan2", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetTransacstionById_Result> VT_GetTransacstionById4(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTransacstionById_Result>("VT_GetTransacstionById4", idParameter);
        }
    
        public virtual ObjectResult<VT_GetTruckInFo_Result> VT_GetTruckInFo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTruckInFo_Result>("VT_GetTruckInFo", idParameter);
        }
    
        public virtual ObjectResult<VT_GetTruckInFo_Result> VT_GetTruckInFo1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTruckInFo_Result>("VT_GetTruckInFo1", idParameter);
        }
    
        public virtual ObjectResult<VT_DailyPlan_Result> VT_DailyPlan3(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_DailyPlan_Result>("VT_DailyPlan3", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetTripOrder_Result> VT_GetTripOrder1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTripOrder_Result>("VT_GetTripOrder1", idParameter);
        }
    
        public virtual ObjectResult<VT_DailyPlan_Result> VT_DailyPlan4(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_DailyPlan_Result>("VT_DailyPlan4", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_GetTripByDate_Result> VT_GetTripByDate4(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_GetTripByDate_Result>("VT_GetTripByDate4", startParameter, endParameter);
        }
    
        public virtual ObjectResult<VT_DailyPlan_Result> VT_DailyPlan5(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VT_DailyPlan_Result>("VT_DailyPlan5", startParameter, endParameter);
        }
    }
}
